### PR TITLE
Adjust the copy in the auth dialog to remove commas

### PR DESCRIPTION
**Pull request by springmeyer**
Currently the commas in the text used on the Auth dialog do not render correctly on MacOS machines using the official (intel-based) Qgis 3.34 installer from https://www.qgis.org/en/site/forusers/download.html.

Current:
Screenshot 2024-02-27 at 6 55 56 PM

Expected:
Screenshot 2024-02-27 at 6 56 08 PM

This addresses the issue by simplifying the language to avoid needing commas.

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by springmeyer** [comment]
Thanks for the ✅ @nyalldawson! I noticed this failed on CI, so before merging I started working on a fix for the CI job, see https://github.com/felt/qgis-plugin/pull/61.

**Comment by springmeyer** [comment]
Okay, CI is passing now, so I'll plan to merge this soon. @nyalldawson how about this one goes into a 2.0.1 milestone? (which could be this and any other small fixes that come up soon) and then additional new features could go into a 3.0.0 milestone - let me know if that sounds good to you.

**Comment by nyalldawson** [comment]
@springmeyer fine by me. Want me to push 2.0.1 now?

**Comment by springmeyer** [comment]
> @springmeyer fine by me. Want me to push 2.0.1 now?

👍🏼 sounds great, thanks!

**Pull request merged**
